export const NavLinks = [
    {
        id:1,
        url:"#home",
        label:"Home",
    },
    {
        id:2,
        url:"#services",
        label: "Expertise",
    },
    {
        id:3,
        url:"#resume",
        label:"Experience",
    },
    {
        id:4,
        url:"#work",
        label:"Projects",
    },
    {
        id:5,
        url:"#skills",
        label:"Skills",
    },
    {
        id:6,
        url:"#testimonials",
        label:"Blogs",
    },
    {
        id:7,
        url:"#contact",
        label:"Contact",
    },
]
